name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 3.81.233.4
          username: ec2-user
          key: \${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd ~/aws-automation/docker
            
            # Pull latest code changes
            git pull origin main
            
            # Build the Docker image locally on EC2
            docker build -t my-nginx .
            
            # Stop and remove any existing container
            docker stop my-nginx-container || true
            docker rm my-nginx-container || true
            
            # Run the new container
            docker run -d -p 80:80 --name my-nginx-container my-nginx
